[package]
name = "zkm2-prover"
description = "zkMIPS"
readme = "../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
p3-matrix = { workspace = true }
zkm2-recursion-compiler = { workspace = true }
zkm2-recursion-core = { workspace = true }
zkm2-recursion-circuit = { workspace = true }
zkm2-recursion-gnark-ffi = { workspace = true }
zkm2-core-machine = { workspace = true }
zkm2-stark = { workspace = true }
p3-symmetric = { workspace = true }
zkm2-core-executor = { workspace = true }
zkm2-primitives = { workspace = true }
p3-field = { workspace = true }
p3-challenger = { workspace = true }
p3-koala-bear = { workspace = true }
p3-bn254-fr = { workspace = true }
p3-commit = { workspace = true }
bincode = "1.3.3"
serde = { workspace = true, features = ["derive", "rc"] }
itertools = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = "0.2.3"
serde_json = { workspace = true }
clap = { version = "4.5.9", features = ["derive", "env"] }
anyhow = "1.0.83"
dirs = "5.0.1"
serial_test = "3.1.1"
num-bigint = "0.4.6"
thiserror = "1.0.63"
lru = "0.12.4"
eyre = "0.6.12"
test-artifacts = { workspace = true, optional = true }

[dev-dependencies]
test-artifacts = { workspace = true }

[[bin]]
name = "build_plonk_bn254"
path = "scripts/build_plonk_bn254.rs"

[[bin]]
name = "build_groth16_bn254"
path = "scripts/build_groth16_bn254.rs"

[[bin]]
name = "build_compress_vks"
path = "scripts/build_compress_vks.rs"

[[bin]]
name = "post_trusted_setup"
path = "scripts/post_trusted_setup.rs"

[[bin]]
name = "fibonacci_groth16"
path = "scripts/fibonacci_groth16.rs"
required-features = ["export-tests"]

[[bin]]
name = "fibonacci_sweep"
path = "scripts/fibonacci_sweep.rs"
required-features = ["export-tests"]

[features]
default = ["native-gnark"]
native-gnark = ["zkm2-recursion-gnark-ffi/native"]
export-tests = ["dep:test-artifacts"]
debug = ["zkm2-core-machine/debug"]
